name: "Cache Janitor"
description: "Automatically purges GitHub Actions caches based on specified age and size limits to optimize workflow performance."
inputs:
  debug:
    description: "Set to 'true' to enable detailed debug output during action execution."
    required: false
    default: "false"
  max-age:
    description: 'Delete caches older than this value. Accepts formats like "7d", "1w", "2M".'
    required: false
    default: "7d"
  max-total-size:
    description: 'Maximum total size of caches to retain. Accepts formats like "1GB", "500MB", "10TB".'
    required: false
    default: "10GB"
  accessed:
    description: 'Set to "true" to delete caches based on their last accessed time.'
    required: false
    default: "true"
  created:
    description: 'Set to "true" to delete caches based on their creation time.'
    required: false
    default: "false"
  token:
    description: "Used to communicate with the GitHub API. Typically not supplied by the user."
    required: false
    default: ${{ github.token }}
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "database"
  color: "purple"
