name: CI

"on":
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # -------- THIS ACTION --------
      - name: Purge caches
        uses: ./.
        with:
          debug: true
          # 3 days
          max-age: 259200
      # -------- THIS ACTION --------

      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+date-%Y-%m-%d-time-%H-%M-%S")" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', 'package.json') }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', 'package.json') }}-
      - name: Install packages and build the app
        run: npm ci
      - name: Commit & Push changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git pull --rebase --autostash
          git add dist
          git commit -m "action: build the app" || echo ""
          git push