name: CI

"on":
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  build:
    name: Build and test the action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Cache NPM dependencies
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Install dependencies and build the action
      - name: Install packages & Build the action
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage
      
      - name: Upload coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          destination_dir: coverage
          keep_files: true
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/
      
      # Custom cache purge action
      - name: Purge caches
        uses: ./.
        with:
          debug: true
          created: true
          accessed: true
          max-age: 259200
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push changes
        if: github.event_name == 'push'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch --unshallow
          git checkout master
          git add dist
          git commit -m "action: build the action" || echo "No changes to commit"
          git push